spring:
  application.name: Event Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager_repository
    username: itdev
    password: finalproj
  jpa:
    properties:
      hibernate:
        current_session_context_class: thread
        hbm2ddl:
          auto: update
    open-in-view: false